### ISSUE TITLE
Quick schedule feature

### ISSUE THREAD

**Issue by rrajpuro** [ajaykrish244/ScheduleBot#14]
## Description
As a user of the bot, I would like the ability to quickly schedule an event within the next 24 hours by automatically selecting the first available time slot for a specified event type. This feature would streamline the scheduling process, making it more efficient for users who want to set up events without specifying a precise time.

## Use Case
Imagine a scenario where a user wants to schedule a meeting or appointment for a specific event type (e.g., a team meeting, study session, or gaming session) but doesn't have a preference for the exact timing within the next day. The "Quick Schedule" feature would automatically find and allocate the first available time slot for the chosen event type.

### Event Type Specification:
Users should be able to specify the type of event they want to schedule.
### Automatic Time Slot Selection:
The bot should analyze the calendar or scheduling system and automatically select the first available time slot within the next 24 hours for the specified event type.
### User Confirmation:
Before finalizing the scheduling, the bot should present the selected time slot to the user for confirmation.
### Flexibility:
The feature should be flexible enough to accommodate different event types and user preferences.

## Additional Context:

Are there any specific constraints or considerations that should be taken into account?
How should the bot handle scenarios where there are no available time slots within the next 24 hours for the specified event type?
Potential Implementation Ideas:

Consider incorporating natural language processing (NLP) to allow users to express preferences in a more conversational manner.
Explore options for integrating with external calendars or scheduling APIs to enhance accuracy and availability checking.

**Comment by ajaykrish244** [comment]
Completed and merged it to the main
