### ISSUE TITLE
Missing Python package for MySQL

### ISSUE THREAD

**Issue by rrajpuro** [ajaykrish244/ScheduleBot#2]
## Description:
The mysql-connector-python package is not included in the requirements.txt file, causing issues with MySQL connectivity. Please add the package to ensure proper installation and functionality.

## Expected Outcome:
Successful installation of the mysql-connector-python package when running pip install -r requirements.txt.

**Comment by TelaproluKeerthana** [comment]
The issue has been resolved after implementing the changes mentioned above and closing the issue
