### ISSUE TITLE
Update Getting Started Section and Add Initialization Script

### ISSUE THREAD

**Issue by rrajpuro** [ajaykrish244/ScheduleBot#3]
## Description:
The Getting Started section in the readme lacks essential details on setting up a MySQL server and initializing databases/tables. This omission leads to errors when users input specific SQL statements. To address this, we need to:

1. Update the Getting Started section with detailed instructions on creating a MySQL server.
2. Provide information on initializing databases and creating initial empty tables.
3. Create an initialization script that installs Python dependencies and sets up databases/tables if they don't exist.

## Expected Outcome:
Users can follow clear instructions in the Getting Started section, and the initialization script ensures proper setup, preventing errors related to missing databases/tables.

**Comment by ajaykrish244** [comment]
Fixed #22
